name: bscore_irb
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - dvc
  - pip
  - pip:
      - optbinning
      - pympler
      - mlflow
      - pyspark
      - feature-engine
      - ruff
      - jedi-language-server
