name: bscore_irb
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy==1.26.4
  - pandas
  - scikit-learn
  - matplotlib
  - dvc
  - pip
  - pip:
      - optbinning==0.20.0
      - mlflow
      - pyspark==3.5.6
      - mrmr_selection
      - feature-engine